// Temporary static movies data

// prettier-ignore
export default [
    { rating: "100%", review_count: 65,  title: "Laura" },
    { rating: "100%", review_count: 238, title: "Leave No Trace" },
    { rating: "100%", review_count: 60,  title: "M" },
    { rating: "100%", review_count: 94,  title: "Rebecca" },
    { rating: "100%", review_count: 87,  title: "Seven Samurai" },
    { rating: "100%", review_count: 48,  title: "Shadow of a Doubt" },
    { rating: "100%", review_count: 67,  title: "Singin' in the Rain" },
    { rating: "100%", review_count: 48,  title: "The Adventures of Robin Hood" },
    { rating: "100%", review_count: 47,  title: "The Kid" },
    { rating: "100%", review_count: 60,  title: "The Maltese Falcon" },
    { rating: "100%", review_count: 101, title: "The Philadelphia Story" },
    { rating: "100%", review_count: 42,  title: "Top Hat" },
    { rating: "85%",  review_count: 565, title: "Once Upon a Time In Hollywood" },
    { rating: "89%",  review_count: 455, title: "1917" },
    { rating: "90%",  review_count: 525, title: "A Star Is Born" },
    { rating: "90%",  review_count: 448, title: "Spider-Man: Far From Home" },
    { rating: "90%",  review_count: 478, title: "Star Wars: The Last Jedi" },
    { rating: "91%",  review_count: 464, title: "La La Land" },
    { rating: "91%",  review_count: 407, title: "The Invisible Man" },
    { rating: "91%",  review_count: 417, title: "Widows" },
    { rating: "92%",  review_count: 394, title: "Baby Driver" },
    { rating: "92%",  review_count: 461, title: "Dunkirk" },
    { rating: "92%",  review_count: 393, title: "Spider-Man: Homecoming" },
    { rating: "92%",  review_count: 458, title: "The Shape of Water" },
    { rating: "93%",  review_count: 384, title: "Incredibles 2" },
    { rating: "93%",  review_count: 420, title: "Logan" },
    { rating: "93%",  review_count: 442, title: "Star Wars: Episode VII - The Force Awakens" },
    { rating: "93%",  review_count: 418, title: "The Favourite" },
    { rating: "93%",  review_count: 435, title: "Thor: Ragnarok" },
    { rating: "93%",  review_count: 551, title: "Us" },
    { rating: "93%",  review_count: 467, title: "Wonder Woman" },
    { rating: "94%",  review_count: 433, title: "Arrival" },
    { rating: "94%",  review_count: 542, title: "Avengers: Endgame" },
    { rating: "94%",  review_count: 362, title: "Call Me by Your Name" },
    { rating: "94%",  review_count: 388, title: "Marriage Story" },
    { rating: "94%",  review_count: 360, title: "War for the Planet of the Apes" },
    { rating: "95%",  review_count: 372, title: "12 Years a Slave" },
    { rating: "95%",  review_count: 355, title: "Gravity" },
    { rating: "95%",  review_count: 397, title: "Roma" },
    { rating: "95%",  review_count: 452, title: "The Irishman" },
    { rating: "96%",  review_count: 387, title: "A Quiet Place" },
    { rating: "96%",  review_count: 94,  title: "An American in Paris" },
    { rating: "96%",  review_count: 359, title: "Argo" },
    { rating: "96%",  review_count: 444, title: "BlacKkKlansman" },
    { rating: "96%",  review_count: 524, title: "Black Panther" },
    { rating: "96%",  review_count: 372, title: "Booksmart" },
    { rating: "96%",  review_count: 351, title: "Manchester by the Sea" },
    { rating: "96%",  review_count: 296, title: "Pain and Glory" },
    { rating: "96%",  review_count: 104, title: "Psycho" },
    { rating: "96%",  review_count: 313, title: "The Florida Project" },
    { rating: "96%",  review_count: 114, title: "The Godfather, Part II" },
    { rating: "97%",  review_count: 69,  title: "A Night at the Opera" },
    { rating: "97%",  review_count: 327, title: "Boyhood" },
    { rating: "97%",  review_count: 350, title: "Coco" },
    { rating: "97%",  review_count: 92,  title: "Double Indemnity" },
    { rating: "97%",  review_count: 464, title: "Knives Out" },
    { rating: "97%",  review_count: 67,  title: "La Grande illusion" },
    { rating: "97%",  review_count: 426, title: "Mad Max: Fury Road" },
    { rating: "97%",  review_count: 133, title: "Metropolis" },
    { rating: "97%",  review_count: 435, title: "Mission: Impossible - Fallout" },
    { rating: "97%",  review_count: 109, title: "North by Northwest" },
    { rating: "97%",  review_count: 67,  title: "Nosferatu, a Symphony of Horror" },
    { rating: "97%",  review_count: 391, title: "Spider-Man: Into the Spider-Verse" },
    { rating: "97%",  review_count: 372, title: "Spotlight" },
    { rating: "97%",  review_count: 342, title: "The Farewell" },
    { rating: "97%",  review_count: 132, title: "The Godfather" },
    { rating: "97%",  review_count: 451, title: "Toy Story 4" },
    { rating: "98%",  review_count: 110, title: "A Hard Day's Night" },
    { rating: "98%",  review_count: 126, title: "Alien" },
    { rating: "98%",  review_count: 81,  title: "All Quiet on the Western Front" },
    { rating: "98%",  review_count: 133, title: "E.T. The Extra-Terrestrial" },
    { rating: "98%",  review_count: 396, title: "Get Out" },
    { rating: "98%",  review_count: 374, title: "Inside Out" },
    { rating: "98%",  review_count: 65,  title: "King Kong" },
    { rating: "98%",  review_count: 108, title: "Modern Times" },
    { rating: "98%",  review_count: 390, title: "Moonlight" },
    { rating: "98%",  review_count: 459, title: "Parasite" },
    { rating: "98%",  review_count: 317, title: "Portrait of a Lady on Fire" },
    { rating: "98%",  review_count: 122, title: "Rear Window" },
    { rating: "98%",  review_count: 128, title: "Schindler's List" },
    { rating: "98%",  review_count: 53,  title: "Snow White and the Seven Dwarfs" },
    { rating: "98%",  review_count: 89,  title: "The Best Years of Our Lives" },
    { rating: "98%",  review_count: 303, title: "The Big Sick" },
    { rating: "98%",  review_count: 294, title: "Zootopia" },
    { rating: "99%",  review_count: 102, title: "All About Eve" },
    { rating: "99%",  review_count: 123, title: "Casablanca" },
    { rating: "99%",  review_count: 117, title: "Citizen Kane" },
    { rating: "99%",  review_count: 316, title: "Eighth Grade" },
    { rating: "99%",  review_count: 97,  title: "It Happened One Night" },
    { rating: "99%",  review_count: 398, title: "Lady Bird" },
    { rating: "99%",  review_count: 230, title: "Never Rarely Sometimes Always" },
    { rating: "99%",  review_count: 105, title: "On the Waterfront" },
    { rating: "99%",  review_count: 246, title: "Paddington 2" },
    { rating: "99%",  review_count: 313, title: "Selma" },
    { rating: "99%",  review_count: 226, title: "Shoplifters (Manbiki kazoku)" },
    { rating: "99%",  review_count: 73,  title: "Sunset Boulevard" },
    { rating: "99%",  review_count: 89,  title: "The Battle of Algiers" },
    { rating: "99%",  review_count: 67,  title: "The Cabinet of Dr. Caligari" },
    { rating: "99%",  review_count: 83,  title: "The Third Man" },
    { rating: "99%",  review_count: 145, title: "The Wizard of Oz" },
];
